---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/english/_index.md
  label: Homepage Data (en)
- type: document
  path: exampleSite/content/french/_index.md
  label: Homepage Data (fr)
- type: heading
  label: Blog Post
- type: document
  path: exampleSite/content/english/blog/_index.md
  label: Blog Page (en)
- type: document
  path: exampleSite/content/french/blog/_index.md
  label: Blog Page (fr)
- type: directory
  path: exampleSite/content/english/blog
  label: Post (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: exampleSite/content/french/blog
  label: Post (fr)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Career
- type: document
  path: exampleSite/content/english/career/_index.md
  label: Career Page (en)
- type: document
  path: exampleSite/content/french/career/_index.md
  label: Career Page (fr)
- type: directory
  path: exampleSite/content/english/career
  label: Career (en)
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - career
- type: directory
  path: exampleSite/content/french/career
  label: Career (fr)
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - career
- type: heading
  label: Pricing
- type: document
  path: exampleSite/content/english/pricing.md
  label: Pricing (en)
- type: document
  path: exampleSite/content/french/pricing.md
  label: Pricing (fr)
- type: document
  path: exampleSite/content/english/pricing-2.md
  label: Pricing 2 (en)
- type: document
  path: exampleSite/content/french/pricing-2.md
  label: Pricing 2 (fr)
- type: heading
  label: About
- type: document
  path: exampleSite/content/english/about.md
  label: About (en)
- type: document
  path: exampleSite/content/french/about.md
  label: About (fr)
- type: heading
  label: Contact
- type: document
  path: exampleSite/content/english/contact.md
  label: Contact (en)
- type: document
  path: exampleSite/content/french/contact.md
  label: Contact (fr)
- type: heading
  label: Service
- type: document
  path: exampleSite/content/english/services.md
  label: Service (en)
- type: document
  path: exampleSite/content/french/services.md
  label: Service (fr)
- type: heading
  label: Team
- type: document
  path: exampleSite/content/english/team.md
  label: Team (en)
- type: document
  path: exampleSite/content/french/team.md
  label: Team (fr)
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/french
  label: All Pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Translations
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/config.toml
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.en.toml
  label: Menu (en)
- type: document
  path: exampleSite/config/_default/menus.fr.toml
  label: Menu (fr)
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
